// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.3
//   protoc               v7.36.1
// source: proto/chat.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "chat";

export interface GetParticipantsRequest {
  conversationIds: string[];
}

export interface Member {
  userId: string;
  username: string;
  name: string;
  avatarUrl?: string | undefined;
  lastReadAt: string;
}

export interface ConversationParticipants {
  conversationId: string;
  type: string;
  members: Member[];
}

export interface GetParticipantsResponse {
  conversations: ConversationParticipants[];
}

export const CHAT_PACKAGE_NAME = "chat";

export interface ChatServiceClient {
  getConversationsParticipants(request: GetParticipantsRequest): Observable<GetParticipantsResponse>;
}

export interface ChatServiceController {
  getConversationsParticipants(
    request: GetParticipantsRequest,
  ): Promise<GetParticipantsResponse> | Observable<GetParticipantsResponse> | GetParticipantsResponse;
}

export function ChatServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getConversationsParticipants"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ChatService", method)(constructor.prototype[method], method, descriptor);
      Object.defineProperty(constructor.prototype, method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ChatService", method)(constructor.prototype[method], method, descriptor);
      Object.defineProperty(constructor.prototype, method, descriptor);
    }
  };
}

export const CHAT_SERVICE_NAME = "ChatService";
