// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.3
//   protoc               v7.36.1
// source: proto/message.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'message';

export enum ContentType {
  TEXT = 0,
  IMAGE = 1,
  VIDEO = 2,
  AUDIO = 3,
  UNRECOGNIZED = -1,
}

export enum MessageStatus {
  PENDING = 0,
  SENT = 1,
  DELIVERED = 2,
  READ = 3,
  FAILED = 4,
  UNRECOGNIZED = -1,
}

export interface SendMessageRequest {
  conversationId: string;
  messageId?: string | undefined;
  content?: string | undefined;
  contentType: ContentType;
  fileIds: string[];
}

export interface Recipient {
  userId: string;
  status: MessageStatus;
  updatedAt?: string | undefined;
}

export interface SendMessageResponse {
  messageId: string;
  conversationId: string;
  senderId: string;
  senderName: string;
  senderUsername: string;
  senderAvatarUrl?: string | undefined;
  recipients: Recipient[];
  content?: string | undefined;
  contentType: ContentType;
  fileIds: string[];
  createdAt: string;
  updatedAt: string;
}

export const MESSAGE_PACKAGE_NAME = 'message';

export interface MessageServiceClient {
  sendMessage(request: SendMessageRequest): Observable<SendMessageResponse>;
}

export interface MessageServiceController {
  sendMessage(
    request: SendMessageRequest,
  ):
    | Promise<SendMessageResponse>
    | Observable<SendMessageResponse>
    | SendMessageResponse;
}

export function MessageServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['sendMessage'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('MessageService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
      Object.defineProperty(constructor.prototype, method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('MessageService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
      Object.defineProperty(constructor.prototype, method, descriptor);
    }
  };
}

export const MESSAGE_SERVICE_NAME = 'MessageService';
